---
- name: Install poetry
  shell: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/{{ tooling.version.poetry }}/get-poetry.py | python -
  args:
    creates: "{{ ansible_env.HOME }}/.poetry/bin/poetry"

- name: "Unset existing installation link for poetry in /usr/local/bin"
  file:
    path: "/usr/local/bin/poetry"
    state: absent

- name: "Create symlink for poetry in /usr/local/bin"
  become: true
  file:
    src: "{{ ansible_env.HOME }}/.poetry/bin/poetry"
    path: "/usr/local/bin/poetry"
    state: link
