---
- name: Ensure packages are installed.
  become: true
  apt:
    name: ['git', 'zsh' , 'curl']

- name: Ensure antigen dir exists.
  file:
    path: "{{ antigen_install_dir }}"
    state: directory

- name: Download current version of antigen
  get_url:
    url: https://git.io/antigen
    dest: "{{ antigen_install_path }}"

- name: Create .zshrc file
  template:
    src: templates/bash/zshrc
    dest: bash/zshrc