---
- name: Install kubectl
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: kubectl
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ tooling.version.kubectl }}/bin/darwin/{{ module_architecture }}/kubectl"
    version: "{{ tooling.version.kubectl }}"
    unzip: false
